# Nivell 1 ⭐️

#### Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [2]:
import numpy as np
from numpy import random

In [3]:
def resumEstadistic(array): #this function receives an array as a parameter and show a basic statistics data
    if array.ndim > 1:      #if the array has more than 1 dimension shows an error missage
        print("Array no valida. Introduir array d'una dimensio")
    else:
        print("Resum estadistic basic de les dades de l'array:")
        print()
        print("Mitja:",array.mean()) #compute the arithmetic mean along an axis
        print("Mediana:",np.median(array)) #compute the median along an axis
        print("Coeficient de correlacio:",np.corrcoef(array)) #return Pearson product-moment correlation coefficients
        print("Desviacio estandard:",np.std(array)) #compute the standard deviation along an axis
        
array1 = random.randint(100, size=(5)) #generate a 1D random array with 5 values from 0-100
print("Contingut de la primera array: ",'\n',array1,'\n')

array2 = random.randint(100, size=(3,5)) #generate a 2D random array with 3 rows and 5 values from 0-100
print("Contingut de la segona array: ",'\n',array2,'\n')

print()

resumEstadistic(array1)
print()
resumEstadistic(array2)

Contingut de la primera array:  
 [34 47 13 30 41] 

Contingut de la segona array:  
 [[ 5 94 41  7 95]
 [ 3 88 37 46 61]
 [98 55 34 80 55]] 


Resum estadistic basic de les dades de l'array:

Mitja: 33.0
Mediana: 34.0
Coeficient de correlacio: 1.0
Desviacio estandard: 11.575836902790225

Array no valida. Introduir array d'una dimensio


___

#### Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [4]:
def genCuadrat(mida): #this function receives and integer and generates a random values array of the parameter size
    if mida > 1:
        array = random.randint(100, size=(mida,mida))
        print(array)
    else:
        print("Mida del cuadrat no valida.")
    
genCuadrat(5)

[[82 61 92 11 69]
 [72 12 99 12 28]
 [81 66 93 25 15]
 [36 54 80 89  3]
 [85 31 15  2 64]]


___

#### Exercici 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [11]:
taula = random.randint(100,size=(5,5))
print("Contingut de la taula: ",'\n', taula)
print()
def sumRowCol(taula): #this function recieves an array and sum columns and rows
    print("Suma de les columnes: ", taula.sum(axis=0))
    print("Suma de les files: ", taula.sum(axis=1))
    
sumRowCol(taula)

Contingut de la taula:  
 [[31 20 41 52  4]
 [51 36 68 51 15]
 [11 41 77 69 42]
 [26 74 88 74 59]
 [75 83 85 73 73]]

Suma de les columnes:  [194 254 359 319 193]
Suma de les files:  [148 221 240 321 389]


___

#### Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

Per coeficient de correlacio, o coeficient de correlacio de Pearson, entenem per una estadistica que reflexa el grau de correlacio lineal entre dos variable.

La seva interpretacio s'extreu del valor resultant:
0.8-1.0 --> Correlacio molt forta
0.6-0.8 --> Correlacio forta
0.4-0.6 --> Correlacio moderada
0.2-0.4 --> Correlacio debil
0.0-0.2 --> Correlacio molt debil o sense correlacio

In [12]:
def corrCoef(array1,array2):
    media1 = array1.mean()
    media2 = array2.mean()
    standard1 = array1.std()
    standard2 = array2.std()
    
    corr = ((array1*array2).mean()-media1*media2)/(standard1*standard2)
    return corr

prueba1 = np.array([0,1,2])
prueba2 = np.array([2,3,4])

corrCoef(prueba1,prueba2)

0.9999999999999998

___